<%
' App Constants
'*********************************************
Const GLOB_DEBUG = "no"
Const GLOB_PRODUCTION = "yes"
'Const ALLOW_ASPQMAIL = "no"
'Const ALLOW_SSL = "no"
Const HREF_SSL = "https://bellerophon.ntsecure.net/passwordsupport/"
Const HREF_TEST_HOME = "http://localhost/passwordsupport/"
Const HREF_HOME = "http://localhost/passwordsupport/"
Const HREF_PROD_HOME = "http://www.passwordsupport.com"

Const PAGE_HOME = "psfp.htm"
Const PAGE_LOGIN = "Login.asp"
Const PAGE_LOGOUT = "Logout.asp"
Const PAGE_USERMAIN = "UserMain.asp"
Const PAGE_USERPROFILE = "UserProfile.asp"
Const PAGE_USERPREF = "UserPref.asp"
Const PAGE_DATAPASSWORD = "DataPassword.asp"
Const PAGE_DATANOTE = "DataNote.asp"
Const PAGE_DATACALENDAR = "DataCalendar.asp"
Const PAGE_DATABUSINESS = "DataBusiness.asp"
Const PAGE_DATABUSINESSPHONE = "DataBusinessPhone.asp"
Const PAGE_DATABUSINESSEMAIL = "DataBusinessEmail.asp"
Const PAGE_DATABUSINESSADDRESS = "DataBusinessAddress.asp"
Const PAGE_DATAMYADDRESS = "DataMyAddress.asp"
Const PAGE_DATAFRIEND = "DataFriend.asp"
Const PAGE_DATAFRIENDEMAIL = "DataFriendEmail.asp"
Const PAGE_DATAFRIENDPHONE = "DataFriendPhone.asp"
Const PAGE_DATAFRIENDADDRESS = "DataFriendAddress.asp"
Const PAGE_SIGNUP = "Signup.asp"
Const PAGE_GCPURCHASE = "GCPurchase.asp"
Const PAGE_GCREDEEM = "GCRedeem.asp"
Const PAGE_FTSIGNUP = "FTSignup.asp"
Const PAGE_PRODUCTS = "Products.htm"
Const PAGE_UPHELP = "UPHelp.htm"
Const PAGE_FORGOT = "forgot.asp"
Const PAGE_GC = "GC.asp"

Const COLOR_BLUEGRAY = "#6699CC"
Const COLOR_LIGHTBLUE = "#99CCFF"

Const TZID_CENTRAL = 1
Const TZ_DESC = 2
Const TZ_OFFSET = 1
Const SERVER_GMT_OFFSET = -360      'Central Time is -6:00 GMT which is -360 minutes

Const ESC_TILDY = "X#Z@01"
Const ESC_PIPE = "X#Z@02"
Const ESC_CARROT = "X#Z@03"
Const ESC_SQ = "X#Z@04"

Const PAGE_PSERROR = "PSError.asp"
Const PAGE_500100ERROR = "500-100.asp"

Const ACTION_LOGIN_VALIDATE = "alogv_574hff"
Const ACTION_SIGNUP_VALIDATE = "asigv_483fbf"
Const ACTION_LOGIN = "alog_7fg4"
Const ACTION_MAIN = "am_576fhhd"
Const ACTION_MAIN_VALIDATE_PAGESELECT = "amvps_576fhhd"
Const ACTION_MAINSUB = "ams_qgn574"
Const ACTION_MAINSUB_AFTER = "amsa_5e574"
Const ACTION_ADDNEW = "aan_5784hdh"
Const ACTION_VIEW = "av_hf823"
Const ACTION_VIEW_FROM_SUB = "avfs_3ughef"
Const ACTION_VIEW_CANCEL = "avc_h6y3"
Const ACTION_EDIT = "ae_hg743"
Const ACTION_DELETE = "ad_gfh4637"
Const ACTION_VALIDATE_ADDNEW = "avan_ghty56473"
Const ACTION_VALIDATE_EDIT = "ave_459u5ht"
Const ACTION_VALIDATE_DELETE = "avd_45h3y"
Const QSVAR_X1 = "x1"
Const ACTION_LOGOUT_GOHOME = "algh_t895g"
Const ACTION_LOGOUT_NORMAL = "aln_gfjhd97"
Const ACTION_LOGOUT_GOLOGIN = "algl_3t8hf"

Const ACTION_REGSIGNUP = "ars_wifvnv"
Const ACTION_GCSIGNUP = "agcs_wgejnv"
Const ACTION_RMSIGNUP = "arms_gfh8ef"
Const ACTION_DDSIGNUP = "arms_gfh7ef"

Const VALERR_FRIEND_ADDNEW_NO_FN = 908
Const VALERR_FRIEND_ADDNEW_NO_LN = 909
Const VALERR_FRIEND_ADDNEW_INVALID_FN = 910
Const VALERR_FRIEND_ADDNEW_INVALID_LN = 911
Const USERNAME_MIN_LENGTH = 5
Const USERNAME_MAX_LENGTH = 50
Const PASSWORD_MIN_LENGTH = 8
Const PASSWORD_MAX_LENGTH = 15

Const ERR_INVALID_PWD = 998
Const ERR_INVALID_UID = 999 
Const ERR_INVALID_SESSION_ID = 902
Const ERR_INVALID_LOGIN_DATE = 903
Const ERR_INVALID_ACTION = 916
Const ERR_INVALID_LAST_PAGE = 917
Const ERR_NO_LOGIN = 918
Const ERR_UNKNOWN = 919
Const ERR_INVALID_ERR = 927


Const ERR_GET_USERDATA_SPEC = 904
Const ERR_GET_USERDATA_DESC = 905
Const ERR_ADDNEW_USERDATA = 906
Const ERR_EDIT_USERDATA = 907
Const ERR_DELETE_USERDATA = 924
Const ERR_DBINSERT_USERLOGIN = 920
Const ERR_DBDELETE_USERDATA = 921
Const ERR_INVALID_VAP_RC = 922
Const ERR_DBINSERT_USERLOGOUT = 923
Const ERR_NO_USERDATA_SPEC_INCOOK = 925
Const ERR_NO_USERDATASPEC = 925
Const ERR_UNKNOWN_VALERR = 926
Const ERR_INVALID_SUBMIT = 928
Const ERR_GET_CALENDARMONTH_FROM_DB = 929
Const ERR_INVALID_CURDATE = 930
Const ERR_GET_MONTHINFO_FROM_DB = 931
Const ERR_GET_MONTHINFO_FROM_COOKIE = 932
Const ERR_INVALID_CALENDARFREQ = 933
Const ERR_GET_TIMEZONE = 934
Const ERR_INVALID_USERAGENT = 935
Const ERR_INVALID_CASE = 936
Const ERR_GET_STATES = 937
Const ERR_GET_CCTYPE = 938
Const ERR_INVALID_SERVICETYPE = 939
Const ERR_GET_DCCOLOR = 940
Const ERR_ACCESS_VIOLATION = 941
Const ERR_GET_ACCTTYPES = 942
Const ERR_SENDEMAIL_ACCTINFO = 943
Const ERR_GET_ACCTINFO = 944
Const ERR_SEND_EMAIL = 945
Const ERR_SEND_FTEMAIL = 946
Const ERR_NO_RM_ID = 947
Const ERR_INVALID_DELIV = 948
Const ERR_NO_PROSPECT = 949

Const COOK_PREF = "cp48383fd"
Const COOK_CALENDAR = "ccla73dnw"
Const COOKKEY_CURDATE = "cd4387fbf"
Const COOK_USERSTATE = "hye39hfhf"
Const COOKKEY_ATID = "gwud72"
Const COOKKEY_AID = "gh5ud72"
Const COOKKEY_DFCAT = "f5jj4yrfy"
Const COOKKEY_DFID = "a767tgbrfy"
Const COOKKEY_DFDESC = "gguh64fy"
Const COOKKEY_DFPID = "a7j385bf"
Const COOKKEY_DFPDESC = "lahfw74"
Const COOKKEY_DFAID = "dj737r"
Const COOKKEY_DFADESC = "gfjg38"

Const COOK_OLDPAGENUM = "opn_39hgbfs"
Const COOK_NEWNUMPAGES = "nnp_39hgbfs"
Const MAX_DESC_PER_PAGE = 9

Const COOK_USERDATA_SPEC = "cDP_4hy"
Const COOK_LAST_PAGE = "cLP_8rhf8"
Const COOK_ERR_CODE = "cEC_8rhf8"

Const USERAGENT_IE = "ua_msie"
Const USERAGENT_NN = "ua_netscape"
Const USERAGENT_OTHER = "ua_other"

Const LEN_DATETIME = 19     ' YYYY-MM-DD HH:MM:SS
Const LOGIN_TIMEOUT = 1200   ' 1200 seconds

Const ACCT_STATUS_PENDPAY = "PENDACT"
Const ACCT_STATUS_GCPEND = "GCPEND"
Const ACCT_STATUS_CANCEL = "CANCEL"
Const ACCT_STATUS_RMDL = "RMDL"
Const ACCT_STATUS_ACTIVE = "ACT"
Const ACCT_TYPE_PSBASIC1 = "PSBASIC1"
Const ACCT_TYPE_PSPREM1 = "PSPREM1"
Const ACCT_TYPE_GCPSBASIC1 = "GCPPSBASIC1"
Const ACCT_TYPE_GCPSPREM1 = "GCPPSPREM1"
Const ACCT_TYPE_GCRMDL = "GCRMDL"
Const ACCT_TYPE_GCPPSBASIC1 = "GCPPSBASIC1"
Const ACCT_TYPE_GCPPSPREM1 = "GCPPSPREM1"
Const ACCT_TYPE_GCRPSBASIC1 = "GCRPSBASIC1"
Const ACCT_TYPE_GCRPSPREM1 = "GCRPSPREM1"
Const ACCT_TYPE_PROMOPREM145 = "PROMOPREM145"
Const ACCT_TYPE_PROMOPREM160 = "PROMOPREM160"
Const ACCT_TYPE_PROMOPREM190 = "PROMOPREM190"
Const ACCT_TYPE_PROMOPREM1365 = "PROMOPREM1365"
Const ACCT_TYPE_GCPRMDL = "GCPRMDL"
Const ACCT_TYPE_RMDL = "RMDL"
Const ACCT_TYPE_FT30 = "FREETRIAL1"

Const PROD_GCRMDL1 = "PROD_GCRMDL1"
Const PROD_RMDL1 = "PROD_RMDL1"
Const PROD_PSBASIC1 = "SVC_PSBASIC1"
Const PROD_PSGCBASIC1 = "SVC_PSGCBASIC1"
Const PROD_PSGCPREM1 = "SVC_PSGCPREM1"
Const PROD_PSPREM1 = "SVC_PSPREM1"

Const VALERR_NO_USERNAME = 700
Const VALERR_NO_PASSWORD = 701
Const VALERR_NO_EMAIL = 702
Const VALERR_NO_QUESTION = 703
Const VALERR_NO_ANSWER = 704
Const VALERR_INVALID_USERNAME = 705
Const VALERR_INVALID_PASSWORD = 706
Const VALERR_INVALID_EMAIL = 707
Const VALERR_CONFIRM_PASSWORD = 708
Const VALERR_CONFIRM_EMAIL = 709
Const VALERR_NO_AGREE = 710
Const VALERR_NO_PACKAGE = 711
Const VALERR_NO_BFIRSTNAME = 712
Const VALERR_NO_BLASTNAME = 713
Const VALERR_NO_BSTREET = 714
Const VALERR_NO_BCITY = 715
Const VALERR_NO_BSTATE = 716
Const VALERR_NO_BZIP = 717
Const VALERR_NO_CCTYPE = 718
Const VALERR_NO_CCNUMBER = 719
Const VALERR_NO_CCNAME = 720
Const VALERR_NO_CCEXP = 721
Const VALERR_INVALID_BZIP = 722  
Const VALERR_NO_TONAME = 723 
Const VALERR_NO_FROMNAME = 724 
Const VALERR_NO_MESSAGE1 = 725 
Const VALERR_NO_PEMAIL = 726
Const VALERR_NO_DELIVERY = 727
Const VALERR_INVALID_PEMAIL = 728 
Const VALERR_CONFIRM_PEMAIL = 729
Const VALERR_NO_REMAIL = 730
Const VALERR_INVALID_REMAIL = 731
Const VALERR_CONFIRM_REMAIL = 732
Const VALERR_INVALID_ACODE = 733
Const VALERR_GCREDEEMED = 734
Const VALERR_GCNOTFOUND = 735
Const VALERR_PROMOEXPIRED = 736

Const VALERROR_DUPE_USERNAME = 223
Const VALERROR_DUPE_EMAIL = 224




%>