<% @LANGUAGE = "VBScript" %>
<% Response.Buffer = True %>

<% 
Dim UID
UID = "guest"
pass = "guest"
%>
<HTML>
<HEAD>
<TITLE>NWHQ Message Board</TITLE>
</HEAD>
<!-- frames -->
<FRAMESET  ROWS="27%,*,40%,4%" FRAMEBORDER="0" BORDER=0 FRAMESPACING="0" BORDER="0">
	    <FRAME NAME="Top" SRC="Message_Top_tour.asp?UID=<%= UID & "&UID=" & pass %>" MARGINWIDTH="0" MARGINHEIGHT="0" SCROLLING="no" FRAMEBORDER="no" NORESIZE>
	    <FRAMESET COLS="16%,*,16%" FRAMEBORDER="0" BORDER=0 FRAMESPACING="0" BORDER="0">
			<FRAME NAME="Left" SRC="Left.htm" MARGINWIDTH="0" MARGINHEIGHT="0" SCROLLING="no" FRAMEBORDER="no" NORESIZE>
			<FRAME NAME="Mn" SRC="Message_Brd_tour.asp?UID=<%= UID %>" MARGINWIDTH="0" MARGINHEIGHT="0" SCROLLING="auto" FRAMEBORDER="yes" NORESIZE>
			<FRAME NAME="Right" SRC="Right.htm" MARGINWIDTH="0" MARGINHEIGHT="0" SCROLLING="no" FRAMEBORDER="no" NORESIZE>
		</FRAMESET>	
		<FRAMESET COLS="16%,*,16%" FRAMEBORDER="0" BORDER=0 FRAMESPACING="0" BORDER="0">
			<FRAME NAME="Left" SRC="Left.htm" MARGINWIDTH="0" MARGINHEIGHT="0" SCROLLING="no" FRAMEBORDER="no" NORESIZE>
			<FRAME NAME="BottomMain" SRC="Bottom1.asp?UID=<%= UID %>" MARGINWIDTH="0" MARGINHEIGHT="0" SCROLLING="no" FRAMEBORDER="no" NORESIZE>
			<FRAME NAME="Right" SRC="Right.htm" MARGINWIDTH="0" MARGINHEIGHT="0" SCROLLING="no" FRAMEBORDER="no" NORESIZE>
		</FRAMESET>	
		<FRAME NAME="Floor" SRC="Right.htm" MARGINWIDTH="0" MARGINHEIGHT="0" SCROLLING="no" FRAMEBORDER="no" NORESIZE>
</FRAMESET>
</HTML>